blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/bdring/FluidNC/wiki/General-Questions
    about: Please read our documentation which answers many questions
  - name: Discord server
    url: https://discord.com/invite/vGhne3QmFZ
    about: Please ask and answer questions on our Discord server.
