name: Feature Request
description: Report a new FluidNC feature
title: "Feature: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Please describe the desired new capability in the forms below.
- type: textarea
  id: feature-description
  attributes:
    label: Feature Description
    description: |
      Tell us, in great detail, how they new feature should work.  If there is an existing system
      that has something similar, you may reference it as supporting information, but please note
      that we have little interest in adding features just because Marlin (for example) has them.
    placeholder: |
      FluidNC needs a way to sense that the dilithium crystals are too hot, in which
      case it should send a text message to Starfleet Command over subspace radio.
  validations:
    required: true
- type: textarea
  id: other-approaches
  attributes:
    label: Other Approaches
    description: |
      Tell us about other ways of solving the problem and why adding the feature directly
      in FluidNC is better.
    placeholder: |
      I tried adding a Arduino-based heat sensor to the dilithium crystal stack.  It correctly
      identified the problem, but it needed to integrate with FluidNC more closely in order
      to reconfigure the ESP32 radio to subspace mode.
  validations:
    required: true