name: FluidNC Continuous Integration (Build Only)
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        pio_env:
          - noradio
          - wifi
          - bt
        # - wifibt
        # - debug
        pio_env_variant:
          - ""
        # - "_s2"
        # - "_s3"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: platformio-${{ runner.os }}
      - name: Build target ${{ matrix.pio_env }}${{ matrix.pio_env_variant }}
        run: pio run -e ${{ matrix.pio_env }}${{ matrix.pio_env_variant }}
